### ISSUE TITLE
[FEAT] 2주차 과제

### ISSUE THREAD

**Issue by seuriseuljjeok** [NOW-SOPT-iOS-Part/YunHeeSeul-assignment#1]
## 🛠 Issue
2주차 과제

## 📝 To-do
- [x] 아이디, 비밀번호 텍스트필드 각각 활성화되었을 때 border 컬러 변경
- [x] 아이디, 비밀번호 텍스트필드의 텍스트가 모두 채워져 있을 때 버튼을 활성화
- [x] 활성화 된 로그인하기 버튼을 클릭했을 때, 데이터 전달
- [x] 비밀번호 텍스트필드 default 값에 security 적용
- [x] 마스크 버튼을 클릭 시, security를 해제
- [x] 클리어 버튼을 클릭 시, 아이디, 비밀번호 텍스트필드를 각각 클리어
- [x] 정규식 추가
- [x] 닉네임 입력하는 Bottom Sheet 구현
- [x] Bottom Sheet에서 저장한 닉네임을 세번째 뷰에서 아이디 대신 보여주기
- [x] 닉네임 생성한 경우와 아닌 경우 분기처리
- [x] 닉네임 텍스트필드가 입력이 되었을 때, 버튼 활성화
- [x] 닉네임 텍스트필드의 텍스트는 한글로 제한
- [x] 닉네임 영어 입력 시 워닝 라벨 추가
