### ISSUE TITLE
[FEAT] 3주차 과제

### ISSUE THREAD

**Issue by seuriseuljjeok** [NOW-SOPT-iOS-Part/YunHeeSeul-assignment#3]
## 🛠 Issue
3주차 세미나 과제

## 📝 To-do
- [x] 전체 UI 구현
- [x] 홈, 실시간, TV프로그램, 영화, 파라마운트+에 스크롤 이동에 따라 화면 좌우 이동
- [x] 이미지 좌우 이동 시 해당 index만큼 이동

찢길 준비 완~!~!
